### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#1]
![quest](https://cloud.githubusercontent.com/assets/20715603/17235703/be1a8058-5575-11e6-90c5-0eb6afdb28f3.png)
![rep](https://cloud.githubusercontent.com/assets/20715603/17235704/be44eb04-5575-11e6-9d12-68e6614ee311.png)
Hi i found a few issue.

the quest log on the right only show a limit of 3 quest
the rep bar is abit off
can you add the gryphons back?

Thanks alot!

**Comment by spiralofhope** [comment]
I made #3 for the quest log.

The rep bar has been fixed either in
https://github.com/spiralofhope/TidyBar/tree/7.0.3.5
or the latest master
https://github.com/spiralofhope/TidyBar/archive/master.zip

Edit TidyBar.lua to turn the gryphons on.

**Comment by stygz** [comment]
May i know the difference between 7.0.3.5 and master? Thx

**Comment by spiralofhope** [comment]
The changelog will have notes.

Github will have sources.  Maybe this link will give it:
https://github.com/spiralofhope/TidyBar/commit/b407afbe4076fd58c8fcd3e76fd0910d6c4ce99d
