### ISSUE TITLE
Fix sidebar alignment when boss frames are displayed

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#12]
when ever there is a unit frame on the right side, the sidebars will mess up and sometimes the quest log will disappear.
Is it possible to not have the sidebars so high up.
![sidebar](https://cloud.githubusercontent.com/assets/20715603/17352384/c387971e-5968-11e6-8fee-3fb398392b1b.png)

**Comment by spiralofhope** [comment]
I didn't notice an issue with the master I was working with earlier.  The fix should be in 7.0.3.7 now

https://github.com/spiralofhope/TidyBar/releases/tag/7.0.3.7

**Comment by stygz** [comment]
Okie thanks. I will check it out and see if it works.
Thanks for the updates.

**Comment by spiralofhope** [comment]
I did some additional tweaking of the tweaking which addresses alignment issues I've seen with the sidebars and the quest log.  It's in [7.0.3.9](https://github.com/spiralofhope/TidyBar/releases/tag/7.0.3.9)

**Comment by spiralofhope** [comment]
I did some more tweaking for 7.0.3.10
