### ISSUE TITLE
Fix reputation bar when resting

### ISSUE THREAD

**Issue by spiralofhope** [spiralofhope/TidyBar#13]
- be outside of a rested area
- show both the experience and the reputation bar
- enter a rested area

The reputation bar and all those above it are shifted to the left and up.

This is probably because there's some sort of special bar I didn't notice, which has to be shifted over or attached to the main xp bar.  Or something.

Disabling and re-enabling the tracking of a reputation fixes this.  So perhaps a brute-force fix is to properly re-check for a reputation change.  I do have the one-liner which is supposed to do this.. I guess it needs to be more broad.

**Comment by stygz** [comment]
i tried disable the rep and restart wow but now the sidebars are mess up.

**Comment by spiralofhope** [comment]
Fixed in 7.0.3.8

@stygz whatever that problem is, I've never seen it.  Open a new ticket if it exists with the latest version.
