### ISSUE TITLE
sidebars

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#16]
This is before
![image](https://cloud.githubusercontent.com/assets/20715603/17389062/5c26cdbc-5a33-11e6-866e-d46fdf949ac3.png)
this is after
![image](https://cloud.githubusercontent.com/assets/20715603/17389030/13fd3652-5a33-11e6-82cf-57954784dc2c.png)
Notice the sidebars mess up randomly and the Exp bar space went up abit. Sometimes in combat and sometimes when i enter a different zone.
I think this is a problem with the exp/honor/rep bar. Maybe u can just try leaving a empty space there even the bars r disable

**Comment by spiralofhope** [comment]
Are you using the latest version?  There's a minor alignment issue but it's not *that* bad.

**Comment by stygz** [comment]
yup using the latest version

**Comment by spiralofhope** [comment]
This should be fixed in 7.0.3.10
