### ISSUE TITLE
Fix reputation bars and mainbar background while in combat

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#17]
Before
![mainbar](https://cloud.githubusercontent.com/assets/20715603/17389293/78fc8556-5a35-11e6-8bf0-a690f84899d3.png)
after
![bar2](https://cloud.githubusercontent.com/assets/20715603/17389294/7cd9bb8a-5a35-11e6-8335-420553900443.png)
Not sure if this is working as intented for the empty bars.

**Comment by spiralofhope** [comment]
Are you using the latest version?  I see no issues under any circumstance.

**Comment by stygz** [comment]
yup i always check for new version and install then.

**Comment by spiralofhope** [comment]
I made an update, but I doubt it'll change this.  I'll keep an eye out for it.

There are some limitations while in combat, but the previous author put in some checks.. maybe I can remove them and keep the bars updated even during combat.

Did you stealth while in combat?  That's a likely culprit.

**Comment by spiralofhope** [comment]
Reputation and mainbars were reworked in 7.0.3.11, and I did some significant testing in combat.

I still suspect things will go wonky when you change forms.  I'm testing.

**Comment by spiralofhope** [comment]
I'm not sure how to test further.  If you see this issue again, comment with the steps to reproduce it.
