### ISSUE TITLE
Bar background

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#4]
Good day, i think you accidentally removed the background for the action bar.
![background](https://cloud.githubusercontent.com/assets/20715603/17270857/4268379a-569f-11e6-9251-fbf40b08ee69.png)

**Comment by stygz** [comment]
actually this looks better haha

**Comment by spiralofhope** [comment]
This is an option at the top of `TidyBar.lua` to enable/disable this.

This feature isn't perfect, and I don't think I can make it perfect.  Blizzard does different things to make those buttons compared to the others.  =/
