### ISSUE TITLE
Support HonorWatchBar

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#45]
![image](https://cloud.githubusercontent.com/assets/20715603/18222046/5c73cb2a-71bd-11e6-9fe1-df6d6e371672.png)
There is an issue with the honor watch bar

**Comment by spiralofhope** [comment]
I wrote some code for this, but I have no way of testing it (I don't and will never PvP).

Try this version:

https://github.com/spiralofhope/TidyBar/archive/master.zip

If you don't want to, you don't have to exit the game to update.  Just delete or rename your folder, extract these files and `/console reloadui`.

If WoW gives no errors but still shows no bar, check the options panel and turn the feature on.

Now that there are up to four bars, I've written some code that will make it easy for me to change what order they are in.  Right now they are

(top)

- reputation
- honor
- artifact
- experience

(bottom)

.. let me know if you want the honor bar in some other place.

**Comment by stygz** [comment]
the honor bar still have some issue but its fine because i can turn it off now. thanks for the update.

**Comment by stygz** [comment]
![1](https://cloud.githubusercontent.com/assets/20715603/18225144/a9108854-721e-11e6-9e08-e5edd881da1c.png)
![2](https://cloud.githubusercontent.com/assets/20715603/18225147/b09c1980-721e-11e6-8694-040e9feadc30.png)
still some issue with the bar.

**Comment by spiralofhope** [comment]
I think I figured that out.  Try this:

https://github.com/spiralofhope/TidyBar/archive/master.zip

**Comment by spiralofhope** [comment]
I'm satisfied with the changes I've made for the upcoming 7.0.3.22.  If there are remaining issues, please re-open this ticket.
