### ISSUE TITLE
Tidybar cant load if char is not max level

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#51]
Good day.

The addon wont load and there is a warning saying tidybar char level not max.

**Comment by spiralofhope** [comment]
Sorry about the delay, but I can't reproduce this.  It works fine for me.

If the message is `TidyBar:  Character is not max level` then you have debugging turned on and that message is normal.

Have you done the usual things like try without other addons and make sure you have the latest version?

**Comment by stygz** [comment]
yup tried everything and still the same. There is no option in my interface menu for tidybar for all my toon below 110.

**Comment by spiralofhope** [comment]
I don't know what to say.  I re-checked, and I have no issues and I have no errors with any character of any level.
